name: Fisrt work-flow for git hub acitions
on: workflow_dispatch
jobs:
  first-job:
      runs-on: ubuntu-latest
      steps:
        - name: hello
          run: echo 'hello ad wellcom o github action
        - name: fair well
          run: echo 'see you next time'  
