name: First workflow for github actions

on:
  push:
    branches: [main]

jobs:
  first-job:
    runs-on: ubuntu-latest
    # these below steps are just simple text messa so thats why we don't need to mention the github checkout@v6
    steps:
      - name: hello
        run: echo "hello and welcome to github actions"

      - name: fair well
        run: echo "see you next time"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job

    steps:
      #  IMPORTANT STEP
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: install dependencies
        run: npm install

  third-job:
    runs-on: ubuntu-latest
    needs: [first-job, second-job]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Welcome
        run: echo "hello and welcome to your application lets run it"

      - name: run the app
        run: node index.js

      - name: fair well
        run: echo "see you next time"
