name: Fisrt work-flow for git hub acitions
on:
  push:
    branches: [main]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo 'hello ad wellcom o github action'
      - name: fair well
        run: echo 'see you next time'
  second-job:
    runs-on: ubuntu-latest
    needs: first-job #this is call synchronus jobs runing this will wait for first-job to complete then it will start
    steps:
      - name: hello
        run: echo 'hello ad wellcom o github action'
      - name: install dependencies
        run: npm install
  third-job:
    runs-on: ubuntu-latest
    needs: [first-job, second-job] #this is call synchronus jobs runing this will wait for first-job and second-job to complete then it will start
    steps:
      - name: Wellcom to run your app
        run: echo 'hello and wellcom to your application lets run it'
      - name: run the app
        run: npm run dev
      - name: fair well
        run: echo 'see you next time'
